quizQuestions = [
'1.) Which sport uses the term \'LOVE\'?',
'2.) What is the German translation for \'WATER\'?',
'3.) In computing what has 8 bits?',
'4.) What is the capital of Brazil?',
'5.) What is the currency of Spain?',
'6.) The German flag has the colors red, gold and ...',
'7.) The most common element in air is ...',
'8.) Which of the following is NOT a gemstone?',
'9.) Which was the longest war ever fought by the US?',
'10.) Which is NOT part of a drum kit?',
'11.) The deepest ocean is the ...',
'12.) How many bones are there in the human body?',
'13.) What is the largest land carnivore?',
'14.) The hammer and anvil are part of the ....',
'15.) What is H2O more commonly known as?',
'16.) Which is the largest country on earth?',
'17.) Who was the first man to step on the moon?',
'18.) Which country has the largest population?',
'19.) Which of the following activites uses up the same ammount calories in 15 minutes as one glass beer?',
'20.) What do you call one golf stroke over par?'
]
